app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, SelectField, BooleanField
from app.models import Category
from wtforms.validators import DataRequired, ValidationError, Length, Email
from .. models import User
from flask_login import current_user, login_user
from app import db


class EditProfileForm(FlaskForm):
    name = StringField('Name', validators=[Length(0,64)])
    username = StringField("Username", validators=[Length(0,64)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    location = StringField('Location', validators=[Length(0,64)])
    bio = TextAreaField("Bio")
    submit = SubmitField("Submit")

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('Sorry! the username is taken. Please choose different one.')

    def validate_email(self, email):
        if email.data!= current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError("Email already exists.")

class AdminLevelEditProfileForm(FlaskForm):
    username = StringField("Username", validators=[Length(0,64)])
    email = StringField("Email", validators=[DataRequired(), Email()])
    confirmed = BooleanField("Confirmed User?")
    role = SelectField("Role", coerce=int, choices=[(1, 'User'), (2, 'Administrator')])
    name = StringField("Name", validators=[Length(0,64)])
    location = StringField('Location', validators=[Length(0,64)])
    bio = TextAreaField("Bio")
    submit = SubmitField("Submit")

    #Without overwriting, the existing username is marked as already exists.
    def __init__(self, original_username, original_email, *args, **kwargs):
        super(AdminLevelEditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username
        self.original_email = original_email

    def validate_username(self, username):
        if username.data != self.original_username:
            user = db.session.query(User).filter_by(
                username=self.username.data).first()
            if user is not None:
                raise ValidationError('Sorry! Username already exists.')
               
    def validate_email(self, email):
        if email.data != self.original_email:
            user = db.session.query(User).filter_by(
                email=self.email.data).first()
            if user is not None:
                raise ValidationError('Sorry! Email already exists.')

     
       

class PostForm(FlaskForm):
    category = SelectField("Category", coerce=int, default=False, validators=[DataRequired()])
    photos = FileField("Photos", validators=[FileAllowed(['jpg', 'png', 'jpeg', 'pdf'])])
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField("Tell us about your free stuff", render_kw={'rows':'10'})
    submit = SubmitField("Submit")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.category.choices = [
            (Category.HOME_LIVING, 'Home&Living'),
            (Category.KITCHEN, 'Kitchen'),
            (Category.BABY, 'Baby'),
            (Category.BOOKS, 'Books'),
            (Category.CRAFT, 'Craft'),
            (Category.ELECTRONICS, 'Electronics'),
            (Category.PETS, 'Pets'),
            (Category.CLOTHING, 'Clothing'),
            (Category.BATHROOM, 'Bathroom'),
            (Category.TOYS, 'Toys'),
            (Category.JEWELLERY, 'Jewellery'),
        ]

class PhotoForm(FlaskForm):
    photo_one = FileField("Photo1", validators=[FileAllowed(['jpg', 'png', 'jpeg', 'pdf'])])
    photo_two = FileField("Photo2", validators=[FileAllowed(['jpg', 'png', 'jpeg', 'pdf'])])
    photo_three = FileField("Photo3", validators=[FileAllowed(['jpg', 'png', 'jpeg', 'pdf'])])
    photo_one_name = StringField("Photo1 filename")
    photo_two_name = StringField("Photo2 filename")
    photo_three_name = StringField("Photo3 filename")
    submit = SubmitField("Submit")

class ContactGiverForm(FlaskForm):
    description = TextAreaField("Any message or inquiry goes here.", validators=[DataRequired()], render_kw={'rows':'10'})
    submit = SubmitField("Submit")

class ReplyForm(FlaskForm):
    description = TextAreaField('Reply message goes here.', validators=[DataRequired()], render_kw={'rows':'10'})
    submit = SubmitField("Reply")

class SearchForm(FlaskForm):
    query = StringField("Query", validators=[DataRequired()])
    submit = SubmitField('Submit')

class ContactAdminForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField("Message", validators=[DataRequired()], render_kw={'rows':'10'})
    submit = SubmitField("Contact")

app/main/__init__.py
from flask import Blueprint
from app.models import Category, Permission


main = Blueprint('main', 
                  __name__,
                  static_folder="/static",
                  static_url_path=""
                )

from . import views, errors



@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

def inject_categories():
    return dict(Category=Category)

app/main/views.py
import datetime
import smtplib
from operator import or_
import secrets
from PIL import Image
from flask import render_template, flash, redirect, request, url_for, current_app, session, send_file
from flask_login import login_required, current_user, fresh_login_required
from app.main.forms import (AdminLevelEditProfileForm, ContactGiverForm, EditProfileForm, 
                            PostForm, ReplyForm, PhotoForm, SearchForm, ContactAdminForm)
from . import main
from app.models import User, Post
from app import db
from ..decorators import permission_required, admin_required
from ..models import Permission, Category, Message, Photo
from app import config
from app.email import send_email
from config import Config
import os
from dotenv import load_dotenv
from werkzeug.utils import secure_filename
from werkzeug.datastructures import  FileStorage
from base64 import b64encode
import boto3

load_dotenv()


def save_photos(form_photos):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_photos.filename)
    photos_fn = random_hex + f_ext
    photos_path = os.path.join(current_app.root_path, 'static/uploads', photos_fn)
    bucket_name = current_app.config['S3_BUCKET_NAME']
    s3 = boto3.resource('s3')
    
    output_size = (500, 500)
    i = Image.open(form_photos)
    i.thumbnail(output_size)
    i.save(photos_path)
    
    s3.meta.client.upload_file(photos_path, bucket_name, photos_fn)
    
    return photos_fn

#Serve image from S3
@main.route('/download/<resource>')
def download_image(resource):
    """ resource: name of the file to download"""
    s3 = boto3.client('s3',
                      aws_access_key_id=current_app.config['AWS_ACCESS_KEY_ID'],
                      aws_secret_access_key=current_app.config['AWS_SECRET_ACCESS_KEY'])

    url = s3.generate_presigned_url('get_object', Params = {'Bucket': current_app.config['S3_BUCKET_NAME'], 'Key': resource}, ExpiresIn = 100)
    return redirect(url, code=302)

@main.route("/", methods=['GET', "POST"])
def index():
    posts = Post.query.all()
    posts_count = Post.query.count()
    
    #Pagination
    page = request.args.get('page', 1, type=int)
    pagination = \
        Post.query.order_by(Post.timestamp.desc()).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/index.html", 
                            posts=posts, 
                            pagination=pagination,
                            posts_count = posts_count,
                            )

@main.context_processor
def base():
    form = SearchForm()
    YEAR = datetime.datetime.now().year
    return dict(form=form, year=YEAR) 

@main.route("/search", methods=['POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():        
        post_query = form.query.data
        results = db.session.query(Post).filter(or_(Post.title.ilike('%' + post_query + '%'), \
                                                (Post.description.ilike('%' + post_query + '%')))).all()
       
        page = request.args.get('page', 1, type=int)
        pagination = \
            db.session.query(Post).filter \
                (or_(Post.title.ilike('%' + post_query + '%'), \
                (Post.description.ilike('%' + post_query + '%')))).paginate(
                page,
                per_page=current_app.config['POSTS_PER_PAGE'],
                error_out=False
            )
        posts = pagination.items
        return render_template('main/search.html', 
                                results=results, 
                                keyword=post_query,
                                pagination=pagination, 
                                posts=posts,
                                )


@main.route("/home-living")
def home_living():
    items = Post.query.filter_by(category_type=Category.HOME_LIVING)
    category="Home&Living"
    page = request.args.get('page', 1, type=int)
   
    pagination = \
        Post.query.filter_by(category_type=Category.HOME_LIVING).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/kitchen")
def kitchen():
    items = Post.query.filter_by(category_type=Category.KITCHEN)
    category="Kitchen"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.KITCHEN).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )
@main.route("/baby")
def baby():
    items = Post.query.filter_by(category_type=Category.BABY)
    category="Baby"
    page = request.args.get('page', 1, type=int)
    
    pagination = \
        Post.query.filter_by(category_type=Category.BABY).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/books")
def books():
    items = Post.query.filter_by(category_type=Category.BOOKS)
    category="Books"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.BOOKS).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/craft")
def craft():
    items = Post.query.filter_by(category_type=Category.CRAFT)
    category="Craft"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.CRAFT).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/electronics")
def electronics():
    items = Post.query.filter_by(category_type=Category.ELECTRONICS)
    category="Electronics"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.ELECTRONICS).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/pets")
def pets():
    items = Post.query.filter_by(category_type=Category.PETS)
    category="Pets"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.PETS).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/clothing")
def clothing():
    items = Post.query.filter_by(category_type=Category.CLOTHING)
    category="Clothing"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.CLOTHING).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/bathroom")
def bathroom():
    items = Post.query.filter_by(category_type=Category.BATHROOM)
    category="Bathroom"
    page = request.args.get('page', 1, type=int)

    pagination = \
        Post.query.filter_by(category_type=Category.BATHROOM).paginate(
            page,
            per_page=current_app.config['POSTS_PER_PAGE'],
            error_out=False
        )
    posts = pagination.items
    return render_template("main/per_category.html", 
                            items=items, 
                            pagination=pagination,
                            posts=posts,
                            category=category,
                            )

@main.route("/toys")
def toys():

app/templates/main/admin_edit_profile.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}{{ super() }} Edit Profile {% endblock %}
{% block category %}{% endblock %}

{% block page_content %}

<div class="post-new-item-div">
<h1>Edit Profile of {{user.username}}</h1>

<form method="POST" novalidate>

 
  {{ form.hidden_tag() }}
    
    <div class="mb-3">
        {{ form.name.label }}
        {{ form.name(class='form-control') }}</div>

    <div class="mb-3">
        {{ form.username.label }}
        {{ form.username(class='form-control')}}

        {% if form.username.errors %}
        {% for error in form.username.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>

      <div class="mb-3">
        {{ form.confirmed() }}
        {{ form.confirmed.label }}
        </div>

        <div class="mb-3">
          {{ form.role.label }}
          {{ form.role(class='form-control') }}
          </div>

      <div class="mb-3">
        {{form.email.label}}
        {{form.email(class="form-control")}}

        {% if form.email.errors %}
        {% for error in form.email.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>


      <div class="mb-3">
        {{form.location.label}}
        {{form.location(class="form-control")}}
      </div>

      <div class="mb-3">
        {{form.bio.label}}
        {{form.bio(class="form-control")}}
      </div>
      
      <button type="submit" class="btn btn-secondary btn-lg button-custom">Edit</button>

</form>

</div>

{% endblock %}

app/templates/main/contact-giver.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}{{super()}}Contact giver {% endblock %}
{% block category %}{% endblock %}

{% block page_content %}
<div class="contact-giver-div">

   <h1><strong style="color:chartreuse;">{{ item.title }}</strong> posted by <strong>{{ item.giver.username }}</strong></h1>
<form class='forms' method="POST">

    {{ form.hidden_tag() }}

    <div class="mb-3">
        
        {{form.description(class="form-control")}}

        {% if form.description.errors %}
        {% for error in form.description.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>

      <button type="submit" class="btn btn-secondary btn-lg button-custom">Send Question</button>
    </form>
    <img class='logo-img2'src="{{ url_for('main.download_image', resource='freestuff_logo.png') }}" alt="freestuff-logo">
</div>
{% endblock %}

app/templates/main/contact_admin.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}{{super()}}Contact Admin{% endblock %}
{% block category %}{% endblock %}

{% block page_content %}
<div class="contact-giver-div">

   <h1>Message to FreeStuff Admin</h1>
<form class='forms' method="POST" novalidate>

    {{ form.hidden_tag() }}

    <div class="mb-3">

      {{form.title.label()}}
      {{form.title(class="form-control")}}

      {% if form.title.errors %}
      {% for error in form.title.errors %}
      <span class="text-danger">{{ error }}</span><br>
      {% endfor %}
      {% endif %}
      </div>

      <div class="mb-3">
      {{form.description.label()}}
      {{form.description(class="form-control")}}

      {% if form.description.errors %}
      {% for error in form.description.errors %}
      <span class="text-danger">{{ error }}</span><br>
      {% endfor %}
      {% endif %}
    </div>

      <button type="submit" class="btn btn-secondary btn-lg button-custom">Send</button>
    </form>

    <img class='logo-img2'src="{{ url_for('main.download_image', resource='freestuff_logo.png') }}" alt="freestuff-logo">
</div>
{% endblock %}

app/templates/main/each_slug_post.html
{% extends 'base.html' %}


{% block title %}{{super()}}{{post.title}}{% endblock %}
{% block category %}{% endblock %}


{% block page_content %}

    <div class="item-div">
        <h1>{{ post.title }}</h1>
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{{ img1 }}" class="d-block w-100 item-image2" alt="{{ post.title }}">
                
              </div>
              <div class="carousel-item">
                <img src="{{ img2 }}" class="d-block w-100 item-image2" alt="{{ post.title }}">
              </div>
              <div class="carousel-item">
                <img src="{{ img3 }}" class="d-block w-100 item-image2" alt="{{ post.title }}">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>

          <div class="card-body info-tab">
            <p><small class="text-muted test">{{ moment.include_moment() }}{{ moment(post.timestamp).fromNow() }}</small></p>
           
          <h5 class="card-title">By  <a href="{{ url_for('main.user', username=post.giver.username)}}">
          {{ post.giver.username }}</h5></a>
          <h3 class="card-text post-description">{{ post.description }}</h3>
          
        </div>
    </div>
    
<div class="category-button-div">
    {% if current_user.is_authenticated and not current_user==post.giver %}
    <a href="{{ url_for('main.contact_giver', item_id=post.id) }}"><button type="button"
            class="btn btn-secondary btn-lg button-custom">Contact {{ post.giver.username }}</button></a>
    {% endif %}
    {% if current_user == post.giver or current_user.is_administrator() %}
    <a href="{{ url_for('main.edit_post', item_id=post.id) }}"><button type="button" class="btn btn-warning edit-button">Edit
            Post</button></a>
    <a href="{{ url_for('main.delete_post', item_id=post.id) }}"><button type="button" class="btn btn-danger delete-button">Delete
            Post</button></a>
    {% endif %}
</div>

<div class="message-div">

    {% if messages %}
        {% for message in post.messages|sort(reverse=True, attribute='timestamp')  %}
            {% if message.reply == False %}
                 <p class="asker">from <strong><a
                href="{{ url_for('main.user', username=message.asker.username)}}">{{ message.asker.username}}</a></strong> --- {{ moment.include_moment() }}{{ moment(message.timestamp).fromNow() }}
                </p>
                 <p class="bubble speech left">{{ message.description }}
                {% if current_user == post.giver%}
                    <a class="reply-tag" href="{{ url_for('main.reply', item_id=post.id, message_id=message.id )}}">Reply</a>{% endif %}
                {% if message.replied == False and current_user == post.giver %}
                    <a href="{{ url_for('main.mark_as_replied', item_id=post.id, message_id=message.id)}}">
                    <button class="btn btn-light button-custom" type="submit">Mark as Replied</button>
                    </a>
                {% endif %}</p>
                
            {% endif %}

       

            {% if message.reply == True %}
                 <p class="giver">from <strong><a
                href="{{ url_for('main.user', username=post.giver.username)}}">{{ post.giver.username}}</a>
                </strong> to {{message.answered_user2}} --- {{ moment.include_moment() }}{{ moment(message.timestamp).fromNow() }}</p>
                <p class="bubble speech right">{{ message.description }}
                    
                {% if message.read == False and message.answered_user == current_user.id %}
                    <a href="{{ url_for('main.mark_as_read', item_id=post.id, message_id=message.id)}}">
                    <button class="btn btn-light button-custom" type="submit">Mark as Read</button>
                {% endif %}
               
                </p>
            {% endif %}
        {% endfor %}
    {% else %}
    <h4>There is no question so far.</h4>
    {% endif %}
</div>


{% endblock %}

app/templates/main/edit-post.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}{{ super() }} Edit Post {% endblock %}
{% block category %}{% endblock %}

{% block page_content %}
<div class="post-new-item-div">
<h1>Edit Your Post "<strong>{{ item.title }}</strong>"</h1>

<form method="POST" enctype=multipart/form-data novalidate>
   
    {{ form.hidden_tag() }}
    {{ p_form.hidden_tag() }}
    
    <div class="mb-3">
        {{ form.category.label }}
        {{ form.category(class='form-control') }}</div>

    <div class="mb-3">
        {{ form.title.label }}
        {{ form.title(class='form-control')}}

        {% if form.title.errors %}
        {% for error in form.title.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>

      <div class="mb-3">
        <div><a href="{{ url_for('main.delete_all_photos', item_id=item.id)}}"><button type="button" class="btn btn-danger delete-button">Delete All Photos</button></a></div>
        {{p_form.photo_one.label}}
        {{p_form.photo_one_name(class="form-control", disabled=disabled, placeholder='No photo uploaded yet')}}
        {{p_form.photo_one(class="form-control")}}

        {% if p_form.photo_one.errors %}
        {% for error in p_form.photo_one.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>


      <div class="mb-3">
        {{p_form.photo_two.label}}
        {{p_form.photo_two_name(class="form-control", disabled=disabled, placeholder='No photo uploaded yet')}}
        {{p_form.photo_two(class="form-control")}}
                
        {% if p_form.photo_two.errors %}
        {% for error in p_form.photo_two.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}

      </div>

      <div class="mb-3">
        {{p_form.photo_three.label}}
        {{p_form.photo_three_name(class="form-control", disabled=disabled, placeholder='No photo uploaded yet')}}
        {{p_form.photo_three(class="form-control")}}

        {% if p_form.photo_three.errors %}
        {% for error in p_form.photo_three.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>

      <div class="mb-3">
        {{ form.description.label }}
        {{ form.description(class='form-control')}}
      </div>
      
      <button type="submit" class="btn btn-secondary btn-lg button-custom">Submit</button>

      </form>

</div>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}

{% block title %}{{super()}}Index {% endblock %}


{% block page_content %}

<div class="index-div">
 
  <h3>Currently we have {{ posts_count }} posts. </h3>
  {% if posts %}
  {% for post in posts|sort(reverse=True, attribute='timestamp') %}

  <div class="card-deck">
    <div class="card col-lg-3 col-md-4 col-sm-12 each-item">
      <a href="{{ url_for('main.each_slug_post', slug=post.slug)}}"> 
        
        <img class="card-img-top item-image" src="{{ url_for('main.download_image', resource=post.photos) }}"
          alt="{{ post.title }}">
        <div class="card-body">
          <h4 class="card-title">{{ post.title }}</h4></a>
      <p class="card-text"><small class="text-muted test">{{ moment.include_moment() }}{{ moment(post.timestamp).fromNow()}}</small></p>
       </div>
    </div>
  {% else %}
  <p>There is no post.</p>
  {% endfor %}
  {% endif %}
</div>

{% endblock %}



{% block pagination %}
{% if pagination %}
<div class="pagination-div">
  {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
{% endblock %}

app/templates/main/per_category.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}

{% block title %}{{super()}}{{category}} {% endblock %}

{% block page_content %}
{{ moment.include_moment() }}
<div class="item-div">

  <h1>Category: {{ category }}</h1>
  {% if items %}
  {% for item in items|sort(reverse=True, attribute='timestamp') %}

  <div class="card-deck">
    <div class="card col-lg-3 col-md-4 col-sm-12 each-item">
      
        <a href="{{ url_for('main.each_slug_post', slug=item.slug)}}">
        <img class="card-img-top item-image" src="{{ url_for('main.download_image', resource=item.photos) }}" alt="{{ item.title }}">
        <div class="card-body">
          <h5 class="card-title">{{ item.title }}</h5></a>
          <p class="card-text"><small class="text-muted test">{{ moment(item.timestamp).fromNow() }}</small></p>
        </div>
    </div>
    {% else %}
<p>There is no item related to {{ category }}.</p>
{% endfor %}
{% endif %}
  </div>

{% endblock %}



{% block pagination %}
{% if pagination %}
<div class="pagination-div">
  {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
{% endblock %}

app/templates/main/reply.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}{{super()}}Reply {% endblock %}
{% block category%}{% endblock %}

{% block page_content %}

<div class="reply-div">

    <h1>This is about <strong>{{ item.title }}</strong>.</h1>
<form method="POST">

    {{ form.hidden_tag() }}

    <div class="mb-3">
        
        {{form.description(class="form-control")}}

        {% if form.description.errors %}
        {% for error in form.description.errors %}
        <span class="text-danger">{{ error }}</span><br>
        {% endfor %}
        {% endif %}
      </div>

      <button type="submit" class="btn btn-secondary btn-lg button-custom">Send Reply</button>

    </form>
</div>
{% endblock %}

app/templates/main/search.html
{% extends 'base.html' %}
{% import "_macros.html" as macros %}

{% block title %}{{super()}}Search result for {{keyword}}{% endblock %}

{% block page_content %}
{{ moment.include_moment() }}

<div class="item-div">
  <h1>Search keyword "<strong>{{ keyword }}</strong>". </h1>
  {% if results %}
  {% for result in results|sort(reverse=True, attribute='timestamp') %}

  <div class="card-deck">
    <div class="card col-lg-3 col-md-4 col-sm-12 each-item">
      
      <a href="{{ url_for('main.each_slug_post', slug=result.slug) }}">
        <div class="img-div">
      <img class="card-img-top item-image" src="{{ url_for('main.download_image', resource=result.photos) }}" alt="{{ result.title }}">
    </div>
      <div class="card-body">
        <h5 class="card-title">{{ result.title }}</h5></a>
        <p class="card-text"><small class="text-muted test">{{ moment(result.timestamp).fromNow() }}</small></p>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <p>There is no item related to the keyword.</p>
   
    {% endif %}
  </div>


  {% endblock %}


  {% block pagination %}
  {% if pagination %}
  <div class="pagination-div">
    {{ macros.pagination_widget(pagination, '.index') }}
  </div>
  {% endif %}
  {% endblock %}